### ISSUE TITLE
How to use ligatures?

### ISSUE THREAD

**Issue by Fastidious** [supernotes/sn-pro#5]
Right now I know that "dash dash greater than" creates an arrow. How what's the shortcut for circled numbers, and the rest of the available ligatures?

**Comment by Fastidious** [comment]
On the same (or similar) note, how to activate "tabular nums"?

**Comment by tobeagram** [comment]
Hi @Fastidious,

Currently only `≤`, `≥`, `≠`, single and double headed arrow ligatures are supported natively in SN Pro.

Circled numbers have not been added to the ligature spec. This is because writing (1), (2), (3) is often more preferable to keep as is. Rather than adding them as ligatures, we're relying on text editors to add support for this, or you can configure text replacement shortcuts in your OS.

Tabular numbers, however, can be activated by enabling Tabular numbers in your text editor or by enabling the `font-feature-settings: 'tnum' 1` in CSS if you're writing code.

**Comment by Fastidious** [comment]
Thank you!
